server:
  port: 8080
  connection-timeout: 30s
spring:
  datasource:
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/forum?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  output:
    ansi:
      enabled: always
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 2




logging:
  file: ./logs/runtime.log